_LCDWC	DATA 	0FF80h
_LCDWD	DATA	0FF81h
_LCDRC	DATA	0FF82h
_LCDRD	DATA	0FF83h

_MENU_OSTATNIE	DATA	035h
_MENU	DATA	030h
_HH	DATA	031h
_MM	DATA	032h
_SS	DATA	033h


_PRZYCISK	DATA	034h
_JED		DATA	036h
_DZI		DATA	037h
_SET		DATA	038h

_JEDO		DATA	043h
_DZIO		DATA	042h
_SETO		DATA	041h
_INDEKS		DATA	040h

_RECV_FLG	BIT 00h


_CSKB0	EQU	0FF21h
_CSKB1	EQU	0FF22h

	
	ORG 0000h
_RESET:
	LJMP _INIT

	ORG 0023h
_INIT_SERIAL_RI:
	MOV A,#_INDEKS
	INC _INDEKS
	ADD A,_INDEKS

	MOV R1,A
	MOV A,SBUF
	MOV @R1,A
	
	CLR RI
	SETB _RECV_FLG
	RETI
	ORG 0100h
_INIT:
	MOV _PRZYCISK,#0	;ustwaiony na nie nacisniety
	CALL _LCD_INIT
	MOV _JED,#0d
	MOV _DZI,#0d
	MOV _SET,#0d

	MOV _MENU,#11	; -MSG, 1 -SETTINGS, 2 -TEST ...
	MOV _MENU_OSTATNIE,#11
	CALL _MENU_WYSWIETLANIE
	;ustawienia do transmisji 
	;z prędkością 9600, 8 bitami danych, 1 bitem stopu
	;MO  M1  M2  REN  TB8  RB8  TI  RI
	MOV SCON,#01010000b;M0=0,  M1=1,  M2=0,  REN=1,  TB8=0,  RB8=0,  TI=0,  RI=0	
	;ustawienie ukladu czasowo-licznikowego T1
	ANL TMOD,#00101111b;GATE1=0, CT1=0, T1M1=?, T1M0=0, GATE0=?, CT0=?, T0M1=?, T0M0=?
	ORL TMOD,#00100000b;GATE1=?, CT1=?, T1M1=1, T1M0=?, GATE0=?, CT0=?,  T0M1=?, T0M0=?

	MOV TL1,#0FDh
	MOV TH1,#0FDh
	ANL PCON,#01111111b
	CLR TF1		
	SETB TR1	;zgoda na zliczanie przez TIMER1/uruchomienie licznika
	
	SETB TI		;zakończenie zleconej transmisji wychodzącej ramki
	CLR RI		;zakończenie transmisji przychodzącej ramki

	SETB ES 
	SETB EA

	CLR _RECV_FLG
	MOV _INDEKS,#0

	MOV _SETO,#48
	MOV _JEDO,#48
	MOV _DZIO,#48

_LOOP:
	JNB _RECV_FLG,_LOOP0
	
	MOV A,_INDEKS
	CLR C
	SUBB A,#3d	
	JC _LOOP00
	MOV _INDEKS,#0d
	MOV _MENU_OSTATNIE,#0	;odswiezam wyswietlacz
_LOOP00:
	CLR _RECV_FLG
_LOOP0:
	CALL _PRZYCISKI
	MOV A,_MENU
	CJNE A,_MENU_OSTATNIE, _LOOP1
	LJMP	_LOOP
_LOOP1:
	MOV _MENU_OSTATNIE,_MENU
	CALL _MENU_WYSWIETLANIE
	LJMP	_LOOP

_ODBIERZ:
	JNB RI,_ODBIERZ_END
	MOV _SETO,SBUF
	CLR RI
	JNB RI,_ODBIERZ_END
	MOV _DZIO,SBUF
	CLR RI
	JNB RI,_ODBIERZ_END
	MOV _JEDO,SBUF
	CLR RI
_ODBIERZ_END:
	RET


_PRZYCISKI:
	CLR C
	MOV A,_MENU
				;0
	JZ _PRZYCISKI_MAIN_MENU
	SUBB A,#1		;1
	JZ _PRZYCISKI_MAIN_MENU
	SUBB A,#1		;2
	JZ _PRZYCISKI_MAIN_MENU
	SUBB A,#1		;3
	JZ _PRZYCISKI_MSG
	SUBB A,#1		;4
	JZ _PRZYCISKI_MSG
	SUBB A,#1		;5
	CALL _PRZYCISKI_CZ2
_PRZYCISKI_END:
	RET

_PRZYCISKI_MAIN_MENU:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK	
	MOV A,R6
	LJMP _PRZYCISKI_END
_SKOK:
	;patrze ktory przycisk jest nacisniety
	MOV _PRZYCISK,A
	JNB ACC.4, _PRZYCISK_UP_MENU
	MOV A,_PRZYCISK
	JNB ACC.5, _PRZYCISK_DOWN_MENU
	MOV A,_PRZYCISK
	JNB ACC.7, _PRZYCISK_ENTER_MENU
	MOV A,R6
	RET

_PRZYCISK_UP_MENU:
	MOV A,_MENU
	JZ _PRZYCISK_UP_MENU1
	DEC _MENU
	RET
_PRZYCISK_UP_MENU1:
	MOV _MENU,#2
	RET
	
_PRZYCISK_DOWN_MENU:
	CLR C
	MOV A,#2
	SUBB A,_MENU
	JZ _PRZYCISK_DOWN_MENU1
	INC _MENU
	RET
_PRZYCISK_DOWN_MENU1:
	MOV _MENU,#0
	RET

_PRZYCISK_ENTER_MENU:
	CLR C
	MOV A,_MENU
	JNZ _PRZYCISK_ENTER_MENU1
	MOV _MENU,#3
_PRZYCISK_ENTER_MENU1:
	SUBB A,#1
	JNZ _PRZYCISK_ENTER_MENU2
	MOV _MENU,#5
_PRZYCISK_ENTER_MENU2:
	SUBB A,#1
	JNZ _PRZYCISK_ENTER_MENU3
	MOV _MENU,#7
_PRZYCISK_ENTER_MENU3:	
	RET

_PRZYCISKI_MSG:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK1
	MOV A,R6
	LJMP _PRZYCISKI_END
_SKOK1:
	MOV _PRZYCISK,A
	JNB ACC.4, _PRZYCISK_UP_MSG
	MOV A,_PRZYCISK
	JNB ACC.5, _PRZYCISK_DOWN_MSG
	MOV A,_PRZYCISK
	JNB ACC.6, _PRZYCISK_ESC_MSG
	MOV A,_PRZYCISK
	JNB ACC.7, _PRZYCISK_ENTER_MSG
	MOV A,R6
	RET

_PRZYCISK_ESC_MSG:
	MOV _MENU,#0
	RET

_PRZYCISK_ENTER_MSG:
	CLR C
	MOV A,_MENU
	SUBB A,#3
	JNZ _PRZYCISK_ENTER_MSG1
	MOV _MENU,#3
	;tutaj wysyla wiadomosc do komputera
_ZAJETE:
	JNB TI,_ZAJETE
	CLR TI	
	MOV A,#48
	ADD A,_SET
	MOV SBUF,A
_ZAJETE1:
	JNB TI,_ZAJETE1
	CLR TI	
	MOV A,#48
	ADD A,_DZI
	MOV SBUF,A
_ZAJETE2:
	JNB TI,_ZAJETE2
	CLR TI	
	MOV A,#48
	ADD A,_JED
	MOV SBUF,A

_PRZYCISK_ENTER_MSG1:
	SUBB A,#1
	JNZ _PRZYCISK_ENTER_MSG2
	MOV _MENU,#9
_PRZYCISK_ENTER_MSG2:
	RET

_PRZYCISK_UP_MSG:
	MOV A,_MENU
	CLR C
	SUBB A,#3
	JNZ _PRZYCISK_UP_MSG1
	MOV _MENU,#4
_PRZYCISK_UP_MSG1:
	SUBB A,#1
	JNZ _PRZYCISK_UP_MSG2
	MOV _MENU,#3
_PRZYCISK_UP_MSG2:
	RET

_PRZYCISK_DOWN_MSG:
	CLR C
	MOV A,#4
	SUBB A,_MENU
	JZ _PRZYCISK_DOWN_MSG1
	INC _MENU
	RET
_PRZYCISK_DOWN_MSG1:
	MOV _MENU,#3
	RET
_PRZYCISKI_CZ2:
	CALL _PRZYCISKI_CZ3
	SUBB A,#1		;9
	JZ _PRZYCISKI_READ
	SUBB A,#1		;10
	;JZ 
	SUBB A,#1		;11
	JZ _PRZYCISKI_11_12_13
	SUBB A,#1		;12
	JZ _PRZYCISKI_11_12_13
	SUBB A,#1		;13
	JZ _PRZYCISKI_11_12_13
	RET

_PRZYCISKI_READ:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK11
	MOV A,R6
	LJMP _PRZYCISKI_READ_END
_SKOK11:
	MOV _PRZYCISK,A
	JNB ACC.6, _PRZYCISK_READ_MSG
	MOV A,R6
_PRZYCISKI_READ_END:
	RET

_PRZYCISK_READ_MSG:
	MOV _MENU,#4
	RET

_PRZYCISKI_11_12_13:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK5
	MOV A,R6
	LJMP _PRZYCISKI_11_12_13_END
_SKOK5:
	MOV _PRZYCISK,A
	JNB ACC.4, _PRZYCISK_11_12_13_UP
	MOV A,_PRZYCISK
	JNB ACC.5, _PRZYCISK_11_12_13_DOWN
	MOV A,_PRZYCISK
	JNB ACC.6, _PRZYCISK_11_12_13_ESC
	MOV A,_PRZYCISK
	JNB ACC.2, _PRZYCISK_11_12_13_LEFT
	MOV A,_PRZYCISK
	JNB ACC.3, _PRZYCISK_11_12_13_RIGHT
	MOV A,R6
_PRZYCISKI_11_12_13_END:
	RET

_PRZYCISK_11_12_13_ESC:
	MOV _MENU,#6
	RET

_PRZYCISK_11_12_13_LEFT:
	MOV A,_MENU
	CLR C
	SUBB A,#11
	JZ _PRZYCISK_11_12_13_LEFT1
	DEC _MENU
	RET
_PRZYCISK_11_12_13_LEFT1:
	MOV _MENU,#13
	RET

_PRZYCISK_11_12_13_RIGHT:
	CLR C
	MOV A,#13
	SUBB A,_MENU
	JZ _PRZYCISK_11_12_13_RIGHT1
	INC _MENU
	RET
_PRZYCISK_11_12_13_RIGHT1:
	MOV _MENU,#11
	RET

_PRZYCISK_11_12_13_UP:
	CLR C
	MOV A,_MENU
	SUBB A,#11
	JNZ _12
	;zwiekszanie setek
	MOV A,_SET
	SUBB A,#9
	JZ _SET_SKOK
	INC _SET
	SJMP _11_12_13_UP_END
_SET_SKOK:
	MOV _SET,#0
	SJMP _11_12_13_UP_END
_12:
	SUBB A,#1
	JNZ _13
	;zwiekszanie dziesiatek
	MOV A,_DZI
	SUBB A,#9
	JZ _DZI_SKOK
	INC _DZI
	SJMP _11_12_13_UP_END
_DZI_SKOK:
	MOV _DZI,#0
	SJMP _11_12_13_UP_END
_13:
;zwiekszanie jed
	MOV A,_JED
	SUBB A,#9
	JZ _JED_SKOK
	INC _JED
	SJMP _11_12_13_UP_END
_JED_SKOK:
	MOV _JED,#0
_11_12_13_UP_END:
	CALL _MENU_WYSWIETLANIE
	RET

_PRZYCISK_11_12_13_DOWN:
	CLR C
	MOV A,_MENU
	SUBB A,#11
	JNZ _12D
	MOV A,_SET
	;zmniejszanie setek
	JZ _SETKI
	DEC _SET
	SJMP _11_12_13_DOWN_END
_SETKI:
	MOV _SET,#9
	SJMP _11_12_13_DOWN_END
_12D:
	SUBB A,#1
	JNZ _13D
	MOV A,_DZI
	;zmniejszanie dziesiatek
	JZ _DZIESIETNE
	DEC _DZI
	SJMP _11_12_13_DOWN_END
_DZIESIETNE:
	MOV _DZI,#9
	SJMP _11_12_13_DOWN_END
_13D:
	MOV A,_JED
	;zmniejszanie jednosci
	JZ _JEDNOSCI
	DEC _JED
	SJMP _11_12_13_DOWN_END
_JEDNOSCI:
	MOV _JED,#9
_11_12_13_DOWN_END:
	CALL _MENU_WYSWIETLANIE
	RET

_PRZYCISKI_CZ3:
	JZ _PRZYCISKI_SETTINGS
	SUBB A,#1		;6
	JZ _PRZYCISKI_SETTINGS
	SUBB A,#1		;7
	JZ _PRZYCISKI_TEST
	SUBB A,#1		;8
	JZ _PRZYCISKI_TEST
	RET

_PRZYCISKI_SETTINGS:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK2
	MOV A,R6
	LJMP _SETTINGS_END
_SKOK2:
	MOV _PRZYCISK,A
	JNB ACC.4, _PRZYCISK_UP_SETTINGS
	MOV A,_PRZYCISK
	JNB ACC.5, _PRZYCISK_DOWN_SETTINGS
	MOV A,_PRZYCISK
	JNB ACC.6, _PRZYCISK_ESC_SETTINGS
	MOV A,_PRZYCISK
	JNB ACC.7, _PRZYCISK_ENTER_SETTINGS
	MOV A,R6
_SETTINGS_END:
	RET

_PRZYCISK_ENTER_SETTINGS:
	CLR C
	MOV A,_MENU
	SUBB A,#5
	JNZ _PRZYCISK_ENTER_SETTINGS1
	MOV _MENU,#5
_PRZYCISK_ENTER_SETTINGS1:
	SUBB A,#1
	JNZ _PRZYCISK_ENTER_SETTINGS2
	MOV _MENU,#11
_PRZYCISK_ENTER_SETTINGS2:
	RET

_PRZYCISK_ESC_SETTINGS:
	MOV _MENU,#1
	RET

_PRZYCISK_UP_SETTINGS:
	MOV A,_MENU
	CLR C
	SUBB A,#5
	JNZ _PRZYCISK_UP_SETTINGS1
	MOV _MENU,#6
_PRZYCISK_UP_SETTINGS1:
	SUBB A,#1
	JNZ _PRZYCISK_UP_SETTINGS2
	MOV _MENU,#5
_PRZYCISK_UP_SETTINGS2:
	RET

_PRZYCISK_DOWN_SETTINGS:
	CLR C
	MOV A,#6
	SUBB A,_MENU
	JZ _PRZYCISK_DOWN_SETTINGS1
	INC _MENU
	RET
_PRZYCISK_DOWN_SETTINGS1:
	MOV _MENU,#5
	RET

_PRZYCISKI_TEST:
	MOV R6,A
	MOV DPTR,#_CSKB1
	MOVX A,@DPTR
	CJNE A,_PRZYCISK,_SKOK3
	MOV A,R6
	LJMP _TEST_END
_SKOK3:
	MOV _PRZYCISK,A
	JNB ACC.4, _PRZYCISK_UP_TEST
	MOV A,_PRZYCISK
	JNB ACC.5, _PRZYCISK_DOWN_TEST
	MOV A,_PRZYCISK
	JNB ACC.6, _PRZYCISK_ESC_TEST
	MOV A,_PRZYCISK
	JNB ACC.7, _PRZYCISK_ENTER_TEST
	MOV A,R6
_TEST_END:
	RET

_PRZYCISK_ENTER_TEST:
	CLR C
	MOV A,_MENU
	SUBB A,#7
	JNZ _PRZYCISK_ENTER_TEST1
	CPL P1.5
_PRZYCISK_ENTER_TEST1:
	SUBB A,#1
	JNZ _PRZYCISK_ENTER_TEST2
	CPL P1.7
_PRZYCISK_ENTER_TEST2:
	RET

_PRZYCISK_DOWN_TEST:
	CLR C
	MOV A,#8
	SUBB A,_MENU
	JZ _PRZYCISK_DOWN_TEST1
	INC _MENU
	RET
_PRZYCISK_DOWN_TEST1:
	MOV _MENU,#7
	RET

_PRZYCISK_UP_TEST:
	MOV A,_MENU
	CLR C
	SUBB A,#7
	JNZ _PRZYCISK_UP_TEST1
	MOV _MENU,#8
_PRZYCISK_UP_TEST1:
	SUBB A,#1
	JNZ _PRZYCISK_UP_TEST2
	MOV _MENU,#7
_PRZYCISK_UP_TEST2:
	RET

_PRZYCISK_ESC_TEST:
	MOV _MENU,#2
	RET

_MENU_WYSWIETLANIE:
	CALL _LCD_CZYSC
	CLR C
	MOV A,_MENU
	SUBB A,#0		;0
	JZ _WYSWIETLANIE_MSG
	SUBB A,#1		;1
	JZ _WYSWIETLANIE_SETTINGS
	SUBB A,#1		;2
	JZ _WYSWIETLANIE_TEST
	SUBB A,#1		;3
	JZ _WYSWIETLANIE_SEND
	SUBB A,#1		;4
	JZ _WYSWIETLANIE_READ
	SUBB A,#1		;5
	JZ _WYSWIETLANIE_UPTIME
	SUBB A,#1		;6
	JZ _WYSWIETLANIE_EDIT_MSG
	SUBB A,#1		;7
	JZ _WYSWIETLANIE_BUZZER
	SUBB A,#1		;8
	JZ _WYSWIETLANIE_LED
	CALL _MENU_WYSWIETLANIE1
	RET

_WYSWIETLANIE_MSG:
	CALL _NAPISZ_MAIN_MENU
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_MSG
	RET

_WYSWIETLANIE_SETTINGS:
	CALL _NAPISZ_MAIN_MENU
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_SETTINGS
	RET

_WYSWIETLANIE_TEST:
	CALL _NAPISZ_MAIN_MENU
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_TEST
	RET

_WYSWIETLANIE_SEND:
	CALL _NAPISZ_MSG
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_SEND
	RET

_WYSWIETLANIE_READ:
	CALL _NAPISZ_MSG
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_READ
	RET

_WYSWIETLANIE_UPTIME:
	CALL _NAPISZ_SETTINGS
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_UPTIME
	RET

_WYSWIETLANIE_EDIT_MSG:
	CALL _NAPISZ_SETTINGS
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_EDIT_MSG
	RET

_WYSWIETLANIE_BUZZER:
	CALL _NAPISZ_TEST
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_BUZZER
	RET

_WYSWIETLANIE_LED:
	CALL _NAPISZ_TEST
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_ZNAK
	CALL _NAPISZ_LED
	RET

_MENU_WYSWIETLANIE1:
	SUBB A,#1		;9
	JZ _WYSWIETLANIE_WIADOMOSC
	SUBB A,#1		;10
	JZ _WYSWIETLANIE_CZAS
	SUBB A,#1		;11
	JZ _WYSWIETLANIE_1ELEMENT
	SUBB A,#1		;12
	JZ _WYSWIETLANIE_2ELEMENT
	SUBB A,#1		;13
	JZ _WYSWIETLANIE_3ELEMENT
RET

_WYSWIETLANIE_WIADOMOSC:
	CALL _NAPISZ_READ
	CALL _SKOK_2_LINIA
	;CALL _NAPISZ_ZNAK
	CALL _NAPISZ_WIADOMOSC
	RET

_WYSWIETLANIE_CZAS:
	CALL _NAPISZ_CZAS
	RET

_WYSWIETLANIE_1ELEMENT:
	CALL _NAPISZ_KOMUNIKAT
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_1ELEMENT
	RET

_WYSWIETLANIE_2ELEMENT:
	CALL _NAPISZ_KOMUNIKAT
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_2ELEMENT
	RET

_WYSWIETLANIE_3ELEMENT:
	CALL _NAPISZ_KOMUNIKAT
	CALL _SKOK_2_LINIA
	CALL _NAPISZ_3ELEMENT
	RET

_NAPISZ_MSG:
	MOV DPTR,#_MSG_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_SETTINGS:
	MOV DPTR,#_SETTINGS_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_TEST:
	MOV DPTR,#_TEST_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_SEND:
	MOV DPTR,#_SEND_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_READ:
	MOV DPTR,#_READ_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_UPTIME:
	MOV DPTR,#_UPTIME_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_EDIT_MSG:
	MOV DPTR,#_EDIT_MSG_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_BUZZER:
	MOV DPTR,#_BUZZER_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_LED:
	MOV DPTR,#_LED_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_MAIN_MENU:
	MOV DPTR,#_MAIN_MENU_NAPIS
	CALL _NAPISZ_WHILE
	RET

_SKOK_2_LINIA:
	MOV R7,#11000000b
	CALL _LCD_CMD_FROM_R7
	RET

_NAPISZ_ZNAK:
	MOV DPTR,#_ZNAK_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_WIADOMOSC:
	MOV R7,_SETO
	CALL _LCD_DATA_FROM_R7
	MOV R7,_DZIO
	CALL _LCD_DATA_FROM_R7
	MOV R7,_JEDO
	CALL _LCD_DATA_FROM_R7
	RET

_NAPISZ_CZAS:
	MOV DPTR,#_CZAS_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_KOMUNIKAT:
	MOV A,_SET
	ADD A,#48d
	MOV R7,A
	CALL _LCD_DATA_FROM_R7
	MOV A,_DZI
	ADD A,#48d
	MOV R7,A
	CALL _LCD_DATA_FROM_R7
	MOV A,_JED
	ADD A,#48d
	MOV R7,A
	CALL _LCD_DATA_FROM_R7
	RET

_NAPISZ_1ELEMENT:
	MOV DPTR,#_1ELEMENT_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_2ELEMENT:
	MOV DPTR,#_2ELEMENT_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_3ELEMENT:
	MOV DPTR,#_3ELEMENT_NAPIS
	CALL _NAPISZ_WHILE
	RET

_NAPISZ_WHILE:
	CLR A
	MOVC A,@A+DPTR
	MOV R7,A
	JZ _NAPISZ_END
	CALL _LCD_DATA_FROM_R7
	INC DPTR
	SJMP _NAPISZ_WHILE
_NAPISZ_END:
	RET

_LCD_CZYSC:
	MOV R7,#1
	CALL _LCD_CMD_FROM_R7
	RET

_LCD_INIT:
	MOV R7,#00000001b	;Wyczyścisz wyświetlacz.
	CALL _LCD_CMD_FROM_R7
	;DL- 8 bitowa wymiana inf., N- wyswietlanie dwuliniowe, F- roz. 5x7 punktow
	MOV R7,#00110000b	; DL=1, N=1, F=0
	;D- wyswietlanie wlaczone, C kursor pod adresem,B kursor mruga
	CALL _LCD_CMD_FROM_R7
	MOV R7,#00001111b	;D=1, C=1, B=1
	CALL _LCD_CMD_FROM_R7
	;I/D=1 to adres pola DD_ RAM jest zwiększany o 1 po kazdorazowym zapisie lub odczycie danej
	; S=1 to pole wyświetlanych danych jest przesuwane w lewo w przypadku, gdy I/D=1
	MOV R7,#00000110b	;I/D=1, S=0
	CALL _LCD_CMD_FROM_R7 
	;S/C=1 to przesuwanie dotyczy pola wyświetlanych danych; gdy S/C=0 to przesuwanie dotyczy kursora
	;R/L=1 to kursor lub pole wyświetlanych danych jest przesuwane w prawo
	;R/L=0 to wykonywane jest przesunięcie w lewą stronę;
	MOV R7,#00010100b	;S/C=0, R/L =1
	CALL _LCD_CMD_FROM_R7	
	
	RET
	
_LCD_WAIT_WHILE_BUSY:
	MOV R1,#_LCDRC
	MOVX A,@R1
	JB ACC.7, _LCD_WAIT_WHILE_BUSY
_LCD_WAIT_WHILE_BUSY_END:
	RET
	
_LCD_CMD_FROM_R7:
	CALL _LCD_WAIT_WHILE_BUSY
	MOV R0,#_LCDWC
	MOV A,R7
	MOVX @R0,A
	RET

_LCD_DATA_FROM_R7:
	CALL _LCD_WAIT_WHILE_BUSY
	MOV R1,#_LCDWD
	MOV A, R7
	MOVX @R1,A
	RET
	
_ZNAK_NAPIS:
	DB	'>',0
_MAIN_MENU_NAPIS:
	DB	'MAIN MENU',0
_MSG_NAPIS:
	DB	'MSG',0
_SETTINGS_NAPIS:
	DB	'SETTINGS',0
_TEST_NAPIS:
	DB	'TEST',0
_SEND_NAPIS:
	DB	'SEND',0
_READ_NAPIS:
	DB	'READ',0
_UPTIME_NAPIS:
	DB	'UPTIME',0
_EDIT_MSG_NAPIS:
	DB	'EDIT_MSG',0
_BUZZER_NAPIS:
	DB	'BUZZER',0
_LED_NAPIS:
	DB	'LED',0
_WIADOMOSC_NAPIS:
	DB	'WIAD',0
_CZAS_NAPIS:
	DB	'CZAS',0
_1ELEMENT_NAPIS:
	DB	'x',0
_2ELEMENT_NAPIS:
	DB	' x',0
_3ELEMENT_NAPIS:
	DB	'  x',0

END